Check that doctrine entities are not final
phpstan/phpstan-doctrine pull request #143
Opened 2020-09-24 06:48 UTC by enumag

I create all my classes as final by default. This however can cause issues with Doctrine:

```
  [Doctrine\Common\Proxy\Exception\InvalidArgumentException]
  Unable to create a proxy for a final class "<entity class>".
```

What do you think about a rule to avoid final entities?

2020-09-24 07:12 UTC, ondrejmirtes requested changes
Yeah, I'm fine with this. Please add it as a bleeding edge rule similar to here: https://github.com/phpstan/phpstan-strict-rules/blob/334898a32217e4605e0f9cfa3d3fc3101bda26be/rules.neon#L67-L69

2020-09-24 07:12 UTC, ondrejmirtes commented on src/Rules/Doctrine/ORM/EntityRule.php
> +		if ($node->isFinal()) {
Ask this first, and only if it's final then continue with checking whether it's an entity etc.

2020-09-24 09:12 UTC, enumag commented
@ondrejmirtes Updated according to your suggestions. Also added a test case.

2020-09-24 09:19 UTC, enumag commented
Hmm... there is already a similar pull request: https://github.com/phpstan/phpstan-doctrine/pull/84

Except I slightly disagree with the statement that entities shouldn't have final methods. I have a case where I'm actually using final method on purpose. But then again I could just disable that particular rule in my codebase.

2020-09-24 12:26 UTC, ondrejmirtes requested changes
I'm fine with the rule in this PR as it is.

2020-09-24 12:26 UTC, ondrejmirtes commented on rules.neon
> +	PHPStan\Rules\Doctrine\ORM\EntityRule:
Please rename the rule to something like `FinalEntityClassRule` and also add it to `services` (without any tags).

I also guess this is the reason why the build failed, so please fix that.

2020-09-24 13:30 UTC, enumag commented
Done. :-)

2020-09-24 13:43 UTC, ondrejmirtes commented on rules.neon
> +	- PHPStan\Rules\Doctrine\ORM\EntityNotFinalRule
It has to be added to `services`. This way you're always registering the rule and the `conditionalTags` section has no effect.

2020-09-25 13:25 UTC, enumag commented
Should be okay now.

2020-09-25 13:34 UTC, merged

2020-09-25 13:34 UTC, ondrejmirtes commented
Thank you!

2020-09-25 13:36 UTC, ondrejmirtes commented
Tagged as 0.12.20.

2020-09-28 19:53 UTC, mhujer commented
@enumag thanks! 👍