Allow JsonType to store any type
phpstan/phpstan-doctrine pull request #195
Opened 2021-06-28 10:56 UTC by simPod

Resolves https://github.com/phpstan/phpstan-doctrine/issues/194

2021-06-28 11:54 UTC, ondrejmirtes commented
This needs a test. You can see how other descriptor changes are tested in commits that changed the same directory: https://github.com/phpstan/phpstan-doctrine/commits/master/src/Type/Doctrine/Descriptors

2021-06-29 08:38 UTC, ondrejmirtes commented
Please test the changes locally before spamming the CI, thanks.

2021-06-29 08:39 UTC, simPod commented
I'm used to leverage CI instead of my local hw so this workflow approvals are breaking my workflow. sorry for that tho.

2021-06-29 12:39 UTC, ondrejmirtes requested changes

2021-06-29 12:39 UTC, ondrejmirtes commented on src/Type/Doctrine/Descriptors/JsonType.php
> +			new StringType(),
Some DRY would be nice here. Also reuse the same `MixedType` instance.

2021-07-01 07:48 UTC, ondrejmirtes approved these changes

2021-07-01 07:48 UTC, merged

2021-07-01 07:49 UTC, ondrejmirtes commented
Thank you!