Add failing tests for `MissingReadOnlyPropertyAssignRule`
phpstan/phpstan-doctrine pull request #339
Opened 2022-05-30 20:40 UTC by herndlm

Closes https://github.com/phpstan/phpstan/issues/7337

Looks like the problem is actually here in `PropertiesExtension` (which is now used at least). https://github.com/phpstan/phpstan-doctrine/blob/1.3.6/src/Rules/Doctrine/ORM/PropertiesExtension.php#L85 returns always `false`, because `$metadata->isReadOnly` (which marks if this is a Doctrine readonly entity?) is already false.

Does this need another early exit dealing with native readonly or smth like that? I gave it a shot, but don't know much about this here. Feel free to finish it :)

2022-05-30 20:50 UTC, herndlm commented on src/Rules/Doctrine/ORM/PropertiesExtension.php
> +		if ($property instanceof PhpPropertyReflection && ($property->isReadOnly() || $property->isReadOnlyByPhpDoc())) {
what if this is another instance? can this be another instance? hmm

2022-05-31 07:16 UTC, herndlm commented on src/Rules/Doctrine/ORM/PropertiesExtension.php
> +		if ($property instanceof PhpPropertyReflection && ($property->isReadOnly() || $property->isReadOnlyByPhpDoc())) {
also: the same or a similar thing might be needed in `isAlwaysWritten` too

2022-05-31 07:26 UTC, ondrejmirtes requested changes
Also the PropertieExtension is completely untested - when I initially wrote it, I was happy it removed all false-positives from a project I test each release with. (And I thought I'll never have to touch it again, haha.)

Can you write a few tests for the current behaviour too? Especially - if the whole entity is marked as readonly by Doctrine metadata + doesn't have a constructor, it means that the entity is inserted into database by other means and the ORM is used only for reading it -> properties should be always initialized. But if it's not readonly / has a constructor, it means the properties should not be initialized.

2022-05-31 07:26 UTC, ondrejmirtes commented on src/Rules/Doctrine/ORM/PropertiesExtension.php
> +		if ($property instanceof PhpPropertyReflection && ($property->isReadOnly() || $property->isReadOnlyByPhpDoc())) {
This logic seems wrong. It's not that `readonly` makes the property initialized, it's that `#[ORM\GeneratedValue]` / `@ORM\GeneratedValue` makes it initialized/always written.

You should look at `$metadata->generatorType` and `$metadata->getIdentifierFieldNames()` IMHO.

2022-06-01 08:26 UTC, herndlm commented on src/Rules/Doctrine/ORM/PropertiesExtension.php
> +		if ($property instanceof PhpPropertyReflection && ($property->isReadOnly() || $property->isReadOnlyByPhpDoc())) {
thx for providing the details! I was actually half-blindly modifying this without knowing much of the surroundings which was a bad idea..

2022-06-01 09:07 UTC, herndlm commented
ok, that looks better I think. The `isAlwaysWritten` and `isAlwaysRead` are still not tested though. Any good test case ideas? Or anything else you need? I can add it here or in follow-ups, whatever is preferred.

2022-06-01 09:59 UTC, herndlm commented
Most of `PropertiesExtension` should be covered now, sorry for the many force-pushes 😅

2022-06-01 12:51 UTC, ondrejmirtes requested changes

2022-06-01 12:51 UTC, ondrejmirtes commented on src/Rules/Doctrine/ORM/PropertiesExtension.php
> +		if ($this->isGeneratedIdentifier($metadata, $propertyName)) {
This exact thing is already checked in this method. I believe if you remove these lines, all tests should still pass.

2022-06-01 12:51 UTC, ondrejmirtes commented on src/Rules/Doctrine/ORM/PropertiesExtension.php
> +		return $metadata->generatorType !== ClassMetadataInfo::GENERATOR_TYPE_NONE;
You can call `$metadata->isIdentifierNatural()` :)

2022-06-01 12:53 UTC, ondrejmirtes commented on tests/Rules/Properties/data/missing-readonly-property-assign-phpdoc.php
> +		$this->doubleAssigned = $doubleAssigned;
I just got an idea for a rule improvement in phpstan/src. If an extension says `isInitialized=true` about a property, even the first assignment should say "readonly property is already assigned" :)

2022-06-01 12:54 UTC, herndlm commented on src/Rules/Doctrine/ORM/PropertiesExtension.php
> +		if ($this->isGeneratedIdentifier($metadata, $propertyName)) {
oh, good find! yeah, they still pass

2022-06-01 12:56 UTC, herndlm commented on tests/Rules/Properties/data/missing-readonly-property-assign-phpdoc.php
> +		$this->doubleAssigned = $doubleAssigned;
interesting, I guess I can take a look at this in phpstan-src

2022-06-01 13:07 UTC, herndlm commented
based on your comments I found another simplification that I did. Not sure why it is there exactly, but I also took over that `getIdentifierFieldNames` exception handling.

2022-06-01 13:09 UTC, herndlm commented on src/Rules/Doctrine/ORM/PropertiesExtension.php
>  		}
hmm this looks risky..

2022-06-01 13:11 UTC, herndlm commented on src/Rules/Doctrine/ORM/PropertiesExtension.php
>  		}
ah ok, that just marks the versioning column in doctrine. I _guess_ it should be fine then since this is not related to the ID

2022-06-01 13:17 UTC, ondrejmirtes approved these changes

2022-06-01 13:18 UTC, ondrejmirtes commented
@herndlm Because ClassMetadata can throw various exceptions and I don't want PHPStan crashing on that. There's a new bleedingEdge rule (https://github.com/phpstan/phpstan-doctrine/blob/1.3.x/src/Rules/Doctrine/ORM/EntityMappingExceptionRule.php) that's gonna tell you if Doctrine doesn't like your mappings.

2022-06-01 13:19 UTC, merged

2022-06-01 13:19 UTC, ondrejmirtes commented
Thank you very much :)

2022-06-01 13:20 UTC, herndlm commented
> @herndlm Because ClassMetadata can throw various exceptions and I don't want PHPStan crashing on that. There's a new bleedingEdge rule (https://github.com/phpstan/phpstan-doctrine/blob/1.3.x/src/Rules/Doctrine/ORM/EntityMappingExceptionRule.php) that's gonna tell you if Doctrine doesn't like your mappings.

thx, makes sense. I assumed something like that, but didn't see the exception in the class/interface and wasn't sure. but I didn't look too long, maybe I just missed it ;)