Add missing throws in stubs
phpstan/phpstan-doctrine pull request #461
Opened 2023-06-26 22:45 UTC by VincentLanglet

Hi @ondrejmirtes,

EntityManagerInterface::getReference throws an ORMException
https://github.com/doctrine/orm/blob/4aadba65cefd4efc89e5946c8b0304656c269a4a/lib/Doctrine/ORM/EntityManagerInterface.php#L182

But this is missing in the stub, so PHPStan reports
```
Foo has Doctrine\ORM\Exception\ORMException in PHPDoc @throws tag but it's not thrown.
```

2023-06-28 20:23 UTC, ondrejmirtes requested changes

2023-06-28 20:23 UTC, ondrejmirtes commented on stubs/EntityManagerInterface.stub
> +     *
Wrong indent

2023-06-28 20:37 UTC, VincentLanglet commented on stubs/EntityManagerInterface.stub
> +     *
Fixed

2023-07-06 12:31 UTC, ondrejmirtes approved these changes

2023-07-06 12:31 UTC, merged

2023-07-06 12:31 UTC, ondrejmirtes commented
Thank you.