Readme: add reportUnknownTypes
phpstan/phpstan-doctrine pull request #524
Opened 2024-01-24 11:03 UTC by janedbal

2024-01-24 11:44 UTC, ondrejmirtes requested changes

2024-01-24 11:44 UTC, ondrejmirtes commented on README.md
> +If you want to be sure you never forget descriptor for some custom type, you can enable:
Please be a little bit more specific here. Show a code example and what error gets reported in that example if this is enabled.

2024-05-28 13:54 UTC, janedbal commented on README.md
> +If you want to be sure you never forget descriptor for some custom type, you can enable:
Example added

2024-05-28 15:41 UTC, merged

2024-05-28 15:41 UTC, ondrejmirtes commented
Thank you!