Append Doctrine proxy class names to list of forbidden class names to…
phpstan/phpstan-doctrine pull request #553
Opened 2024-03-20 13:16 UTC by kamil-zacek

… disallow direct use of Doctrine proxy classes.

2024-03-20 13:19 UTC, ondrejmirtes requested changes

2024-03-20 13:19 UTC, ondrejmirtes commented on tests/Classes/DoctrineProxyForbiddenClassNamesExtensionTest.php
> +		return new InstantiationRule(
I love this! On this line it makes more sense to do `self::getContainer()->getByType(InstantiationRule::class)`. Thanks!

2024-03-20 13:21 UTC, ondrejmirtes commented
Try putting `phpstan/phpstan:1.10.x-dev` in `composer.json` temporarily to verify the build will pass.

2024-03-20 13:37 UTC, kamil-zacek commented on tests/Classes/DoctrineProxyForbiddenClassNamesExtensionTest.php
> +		return new InstantiationRule(
OK, but there is an phpstan error - I don't know how / whether to solve it:

Error: Accessing PHPStan\Rules\Classes\InstantiationRule::class is not covered by backward compatibility promise. The class might change in a minor PHPStan version.
 ------ ----------------------------------------------------------------------------- 
  Line   tests/Classes/DoctrineProxyForbiddenClassNamesExtensionTest.php              
 ------ ----------------------------------------------------------------------------- 
  [18](https://github.com/phpstan/phpstan-doctrine/actions/runs/8359861123/job/22884119180#step:7:19)     Accessing PHPStan\Rules\Classes\InstantiationRule::class is not              
         covered by backward compatibility promise. The class might change in         
         a minor PHPStan version.                                                     
         💡 If you think it should be covered by backward compatibility                
            promise, open a discussion:                                               
         💡 https://github.com/phpstan/phpstan/discussions                             
         💡                                                                            
         💡 See also:                                                                  
         💡                                                                            
            https://phpstan.org/developing-extensions/backward-compatibility-promise

2024-03-21 10:19 UTC, ondrejmirtes approved these changes

2024-03-21 10:19 UTC, merged

2024-03-21 10:20 UTC, ondrejmirtes commented
Awesome, thank you!