Introduce DoctrineTypeDriverAwareDescriptor
phpstan/phpstan-doctrine pull request #578
Opened 2024-06-24 15:12 UTC by janedbal

Separated from https://github.com/phpstan/phpstan-doctrine/pull/506, not yet used.

2024-06-24 15:15 UTC, janedbal commented on src/Type/Doctrine/Descriptors/FloatType.php
> -		return TypeCombinator::union(new \PHPStan\Type\FloatType(), new IntegerType());
I tried hard finding at least single case where integer is returned by some driver (in #506), but was not able to find any. So I believe it was just wrong, int is probably never returned.

On the other hand, numeric-string is returned pretty often and was missing here.

2024-06-24 15:16 UTC, janedbal commented on src/Type/Doctrine/Descriptors/DecimalType.php
> +			new IntersectionType([
numeric-string was missing here, used by most non-sqlite drivers.

2024-06-25 09:34 UTC, ondrejmirtes requested changes

2024-06-25 09:34 UTC, ondrejmirtes commented on src/Type/Doctrine/Descriptors/FloatType.php
> +			|| $driverType === DriverType::PGSQL
in_array would be nicer

2024-06-25 09:34 UTC, ondrejmirtes commented on src/Doctrine/Driver/DriverType.php
> +	public static function detect(Connection $connection, bool $failOnInvalidConnection): ?string
This method should be non-static, DriverType should be injected into descriptors as constructor argument.

`bool $failOnInvalidConnection` should be constructor argument here, `Connection` can still be passed as parameter into `detect()`.

2024-06-25 10:20 UTC, janedbal commented on src/Type/Doctrine/Descriptors/FloatType.php
> -		return TypeCombinator::union(new \PHPStan\Type\FloatType(), new IntegerType());
I'll separate this to another PR.

2024-06-25 10:20 UTC, janedbal commented on src/Type/Doctrine/Descriptors/DecimalType.php
> +			new IntersectionType([
I'll separate this to another PR.

2024-06-25 10:21 UTC, janedbal commented on src/Type/Doctrine/Descriptors/FloatType.php
> +			|| $driverType === DriverType::PGSQL
Done

2024-06-25 10:21 UTC, janedbal commented on src/Doctrine/Driver/DriverType.php
> +	public static function detect(Connection $connection, bool $failOnInvalidConnection): ?string
Done

2024-06-25 11:37 UTC, merged

2024-06-25 11:37 UTC, ondrejmirtes commented
Thank you!